-- お店管理 DB DDL
-- 仕様: DB_SHOPS_SPEC.md

CREATE SCHEMA IF NOT EXISTS shops;

-- ---------------------------------------------------------------------------
-- shops.genres
-- ---------------------------------------------------------------------------
CREATE TABLE shops.genres (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    aid integer NOT NULL,
    name character varying(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT genres_pkey PRIMARY KEY (id),
    CONSTRAINT genres_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT,
    CONSTRAINT genres_id_aid_key UNIQUE (id, aid)
);

CREATE INDEX ix_genres_aid ON shops.genres (aid);

CREATE UNIQUE INDEX uq_genres_aid_name_active
    ON shops.genres (aid, name)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shops
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shops (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    aid integer NOT NULL,
    name character varying(200) NOT NULL,
    address text,
    schedule_memo text,
    last_verified_on date,
    memo text,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shops_pkey PRIMARY KEY (id),
    CONSTRAINT shops_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT,
    CONSTRAINT shops_id_aid_key UNIQUE (id, aid)
);

CREATE INDEX ix_shops_aid ON shops.shops (aid);

CREATE INDEX ix_shops_aid_name_active
    ON shops.shops (aid, name)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shop_genres
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_genres (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    genre_id integer NOT NULL,
    aid integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_genres_pkey PRIMARY KEY (id),
    CONSTRAINT shop_genres_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_genres_genre_aid_fkey FOREIGN KEY (genre_id, aid)
        REFERENCES shops.genres (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_genres_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_shop_genres_shop_genre_active
    ON shops.shop_genres (shop_id, genre_id)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_genres_shop_id
    ON shops.shop_genres (shop_id)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_genres_genre_id
    ON shops.shop_genres (genre_id)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shop_opening_days
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_opening_days (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    day_of_week smallint NOT NULL,
    day_memo text,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_opening_days_pkey PRIMARY KEY (id),
    CONSTRAINT shop_opening_days_day_of_week_check
        CHECK (day_of_week BETWEEN 0 AND 6),
    CONSTRAINT shop_opening_days_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_opening_days_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_shop_opening_days_shop_dow_active
    ON shops.shop_opening_days (shop_id, day_of_week)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_opening_days_shop_id ON shops.shop_opening_days (shop_id);

-- ---------------------------------------------------------------------------
-- shops.shop_opening_slots
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_opening_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    opening_day_id integer NOT NULL,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_opening_slots_pkey PRIMARY KEY (id),
    CONSTRAINT shop_opening_slots_opening_day_fkey FOREIGN KEY (opening_day_id)
        REFERENCES shops.shop_opening_days (id) ON DELETE RESTRICT,
    CONSTRAINT shop_opening_slots_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_opening_slots_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shop_opening_slots_opening_day_id
    ON shops.shop_opening_slots (opening_day_id)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_opening_slots_shop_id ON shops.shop_opening_slots (shop_id);

-- ---------------------------------------------------------------------------
-- shops.shop_menus
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_menus (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    menu_name character varying(200) NOT NULL,
    memo text,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_menus_pkey PRIMARY KEY (id),
    CONSTRAINT shop_menus_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_menus_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shop_menus_shop_id
    ON shops.shop_menus (shop_id)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shop_keywords
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_keywords (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    keyword character varying(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_keywords_pkey PRIMARY KEY (id),
    CONSTRAINT shop_keywords_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_keywords_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_shop_keywords_shop_keyword_active
    ON shops.shop_keywords (shop_id, keyword)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_keywords_aid_keyword_active
    ON shops.shop_keywords (aid, keyword)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shop_stations
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_stations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    transport_type character varying(50) NOT NULL,
    line_name character varying(100),
    station_name character varying(100) NOT NULL,
    walk_minutes smallint,
    distance_memo text,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_stations_pkey PRIMARY KEY (id),
    CONSTRAINT shop_stations_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_stations_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shop_stations_shop_id
    ON shops.shop_stations (shop_id)
    WHERE is_deleted = false;

CREATE INDEX ix_shop_stations_aid_station_active
    ON shops.shop_stations (aid, station_name)
    WHERE is_deleted = false;

-- ---------------------------------------------------------------------------
-- shops.shop_images
-- ---------------------------------------------------------------------------
CREATE TABLE shops.shop_images (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    file_name character varying(255),
    mime_type character varying(100) NOT NULL,
    image_data bytea NOT NULL,
    file_size_bytes integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_images_pkey PRIMARY KEY (id),
    CONSTRAINT shop_images_file_size_bytes_check
        CHECK (file_size_bytes > 0 AND file_size_bytes <= 5242880),
    CONSTRAINT shop_images_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_images_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shop_images_shop_id
    ON shops.shop_images (shop_id)
    WHERE is_deleted = false;
