-- データ構造変更マイグレーション
-- 仕様: for_human/12_shop.txt

-- 定休日フラグ
ALTER TABLE shops.shop_opening_days
    ADD COLUMN IF NOT EXISTS is_closed boolean NOT NULL DEFAULT false;

-- 祝日営業時間
CREATE TABLE IF NOT EXISTS shops.shop_holiday_hours (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    is_closed boolean NOT NULL DEFAULT false,
    memo text,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_holiday_hours_pkey PRIMARY KEY (id),
    CONSTRAINT shop_holiday_hours_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_holiday_hours_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_shop_holiday_hours_shop_active
    ON shops.shop_holiday_hours (shop_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_shop_holiday_hours_shop_id
    ON shops.shop_holiday_hours (shop_id);

CREATE TABLE IF NOT EXISTS shops.shop_holiday_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    holiday_hours_id integer NOT NULL,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_holiday_slots_pkey PRIMARY KEY (id),
    CONSTRAINT shop_holiday_slots_holiday_hours_fkey FOREIGN KEY (holiday_hours_id)
        REFERENCES shops.shop_holiday_hours (id) ON DELETE RESTRICT,
    CONSTRAINT shop_holiday_slots_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_holiday_slots_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_shop_holiday_slots_holiday_hours_id
    ON shops.shop_holiday_slots (holiday_hours_id)
    WHERE is_deleted = false;

-- 来店日
CREATE TABLE IF NOT EXISTS shops.shop_visits (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shop_id integer NOT NULL,
    aid integer NOT NULL,
    visit_date date NOT NULL,
    memo text,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT shop_visits_pkey PRIMARY KEY (id),
    CONSTRAINT shop_visits_shop_aid_fkey FOREIGN KEY (shop_id, aid)
        REFERENCES shops.shops (id, aid) ON DELETE RESTRICT,
    CONSTRAINT shop_visits_aid_fkey FOREIGN KEY (aid)
        REFERENCES public.accounts (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_shop_visits_shop_id
    ON shops.shop_visits (shop_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_shop_visits_shop_date_active
    ON shops.shop_visits (shop_id, visit_date DESC)
    WHERE is_deleted = false;

-- 最寄り駅: 交通機関と路線名を統合
ALTER TABLE shops.shop_stations
    ADD COLUMN IF NOT EXISTS transport_line character varying(150);

UPDATE shops.shop_stations
SET transport_line = CASE
    WHEN line_name IS NOT NULL AND trim(line_name) <> ''
        THEN transport_type || ' ' || line_name
    ELSE transport_type
END
WHERE transport_line IS NULL;

ALTER TABLE shops.shop_stations
    ALTER COLUMN transport_line SET NOT NULL;

ALTER TABLE shops.shop_stations
    DROP COLUMN IF EXISTS transport_type;

ALTER TABLE shops.shop_stations
    DROP COLUMN IF EXISTS line_name;
